export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'; //ALL PRODUCTS
export const FETCH_PRODUCT = 'FETCH_PRODUCT'; //SPECIFIC PRODUCT

export const FETCH_FARMS = 'FETCH_FARMS'; //ALL FARMS
export const FETCH_FARM = 'FETCH_FARM'; //SPECIFIC FARM
